export const SKILL = [
  { value: "Java", label: "Java" },
  { value: "Python", label: "Python" },
  { value: "C++", label: "C++" },
  { value: "JavaScript", label: "JavaScript" },
  { value: "Ruby", label: "Ruby" },
  { value: "React", label: "React" },
  { value: "Angular", label: "Angular" },
  { value: "Vue", label: "Vue" },
  { value: "MySQL", label: "MySQL" },
  { value: "Oracle", label: "Oracle" },
  { value: "SQL Server", label: "SQL Server" },
  { value: "MongoDB", label: "MongoDB" },
  { value: "AWS", label: "AWS" },
  { value: "Azure", label: "Azure" },
  { value: "Google Cloud", label: "Google Cloud" },
  { value: "Docker", label: "Docker" },
  { value: "Kubernetes", label: "Kubernetes" },
  { value: "Jenkins", label: "Jenkins" },
  { value: "Git", label: "Git" },
  { value: "Android", label: "Android" },
  { value: "iOS", label: "iOS" },
  { value: "React Native", label: "React Native" },
  { value: "TensorFlow", label: "TensorFlow" },
  { value: "PyTorch", label: "PyTorch" },
  { value: "Scikit-learn", label: "Scikit-learn" },
  { value: "Network security", label: "Network security" },
  { value: "Application security", label: "Application security" },
  { value: "Agile", label: "Agile" },
  { value: "Scrum", label: "Scrum" },
  {
    value: "User experience (UX) design",
    label: "User experience (UX) design",
  },
  { value: "User interface (UI) design", label: "User interface (UI) design" },
  { value: "HTML", label: "HTML" },
  { value: "CSS", label: "CSS" },
  { value: "SASS", label: "SASS" },
  { value: "LESS", label: "LESS" },
  { value: "Bootstrap", label: "Bootstrap" },
  { value: "Materialize", label: "Materialize" },
  { value: "Semantic UI", label: "Semantic UI" },
  { value: "Foundation", label: "Foundation" },
  { value: "WordPress", label: "WordPress" },
  { value: "Drupal", label: "Drupal" },
  { value: "Magento", label: "Magento" },
  { value: "Shopify", label: "Shopify" },
  { value: "BigCommerce", label: "BigCommerce" },
  { value: "PrestaShop", label: "PrestaShop" },
  { value: "WooCommerce", label: "WooCommerce" },
  { value: "Node.js", label: "Node.js" },
  { value: "Express.js", label: "Express.js" },
  { value: "Socket.IO", label: "Socket.IO" },
  { value: "Meteor.js", label: "Meteor.js" },
  { value: "Ruby on Rails", label: "Ruby on Rails" },
  { value: "Flask", label: "Flask" },
  { value: "Django", label: "Django" },
  { value: "Symfony", label: "Symfony" },
  { value: "Laravel", label: "Laravel" },
  { value: "CakePHP", label: "CakePHP" },
  { value: "Zend", label: "Zend" },
  { value: "ASP.NET", label: "ASP.NET" },
  { value: "MVC", label: "MVC" },
  { value: "Ionic", label: "Ionic" },
  { value: "Flutter", label: "Flutter" },
  { value: "Xamarin", label: "Xamarin" },
  { value: "Swift", label: "Swift" },
  { value: "Objective-C", label: "Objective-C" },
  { value: "Kotlin", label: "Kotlin" },
  { value: "RxJava", label: "RxJava" },
  { value: "RxSwift", label: "RxSwift" },
  { value: "RESTful API", label: "RESTful API" },
  { value: "GraphQL", label: "GraphQL" },
  { value: "SOAP", label: "SOAP" },
  { value: "OAuth", label: "OAuth" },
  { value: "JWT", label: "JWT" },
  { value: "SAML", label: "SAML" },
  { value: "OAuth2", label: "OAuth2" },
  { value: "OpenID Connect", label: "OpenID Connect" },
  { value: "LDAP", label: "LDAP" },
  { value: "Apache Kafka", label: "Apache Kafka" },
  { value: "RabbitMQ", label: "RabbitMQ" },
  { value: "Redis", label: "Redis" },
  { value: "Memcached", label: "Memcached" },
  { value: "Elasticsearch", label: "Elasticsearch" },
  { value: "Logstash", label: "Logstash" },
  { value: "Kibana", label: "Kibana" },
  { value: "Nginx", label: "Nginx" },
  { value: "Apache", label: "Apache" },
  { value: "IIS", label: "IIS" },
  { value: "HAProxy", label: "HAProxy" },
  { value: "Splunk", label: "Splunk" },
  { value: "Graylog", label: "Graylog" },
  { value: "New Relic", label: "New Relic" },
  { value: "Datadog", label: "Datadog" },
  { value: "Grafana", label: "Grafana" },
  { value: "Prometheus", label: "Prometheus" },
  { value: "Zabbix", label: "Zabbix" },
  { value: "Nagios", label: "Nagios" },
  { value: "Ansible", label: "Ansible" },
  { value: "Chef", label: "Chef" },
  { value: "Puppet", label: "Puppet" },
  { value: "SaltStack", label: "SaltStack" },
  { value: "Terraform", label: "Terraform" },
  { value: "CloudFormation", label: "CloudFormation" },
  { value: "Serverless", label: "Serverless" },
  { value: "Lambda", label: "Lambda" },
  { value: "Google Cloud Functions", label: "Google Cloud Functions" },
  { value: "Azure Functions", label: "Azure Functions" },
  { value: "Azure Logic Apps", label: "Azure Logic Apps" },
  { value: "Kubernetes", label: "Kubernetes" },
  { value: "Helm", label: "Helm" },
  { value: "Istio", label: "Istio" },
  { value: "Linkerd", label: "Linkerd" },
  { value: "Prometheus Operator", label: "Prometheus Operator" },
  { value: "Argo CD", label: "Argo CD" },
  { value: "Argo Workflow", label: "Argo Workflow" },
  { value: "GitLab CI/CD", label: "GitLab CI/CD" },
  { value: "Jenkins X", label: "Jenkins X" },
  { value: "Tekton", label: "Tekton" },
  { value: "Spinnaker", label: "Spinnaker" },
  { value: "Kubeflow", label: "Kubeflow" },
  { value: "MLflow", label: "MLflow" },
  { value: "Databricks", label: "Databricks" },
  { value: "Apache Spark", label: "Apache Spark" },
  { value: "Hadoop", label: "Hadoop" },
  { value: "MapReduce", label: "MapReduce" },
  { value: "Hive", label: "Hive" },
  { value: "Pig", label: "Pig" },
  { value: "Mahout", label: "Mahout" },
  { value: "Cloudera", label: "Cloudera" },
  { value: "Hortonworks", label: "Hortonworks" },
  { value: "Confluent", label: "Confluent" },
  { value: "Kafka Connect", label: "Kafka Connect" },
  { value: "Debezium", label: "Debezium" },
  { value: "Schema Registry", label: "Schema Registry" },
  { value: "Apache Flink", label: "Apache Flink" },
  { value: "Apache Beam", label: "Apache Beam" },
  { value: "Airflow", label: "Airflow" },
  { value: "Luigi", label: "Luigi" },
  { value: "Celery", label: "Celery" },
  { value: "RabbitMQ", label: "RabbitMQ" },
  { value: "Apache ActiveMQ", label: "Apache ActiveMQ" },
  { value: "Apache Camel", label: "Apache Camel" },
  { value: "ZeroMQ", label: "ZeroMQ" },
  { value: "Kafka Streams", label: "Kafka Streams" },
  { value: "Akka", label: "Akka" },
  { value: "Apache NiFi", label: "Apache NiFi" },
  { value: "StreamSets", label: "StreamSets" },
  { value: "Apache Calcite", label: "Apache Calcite" },
  { value: "Presto", label: "Presto" },
  { value: "Apache Drill", label: "Apache Drill" },
  { value: "Apache Phoenix", label: "Apache Phoenix" },
  { value: "Apache Ignite", label: "Apache Ignite" },
  { value: "Apache Geode", label: "Apache Geode" },
  { value: "Cassandra", label: "Cassandra" },
  { value: "Couchbase", label: "Couchbase" },
  { value: "MongoDB", label: "MongoDB" },
  { value: "Amazon DynamoDB", label: "Amazon DynamoDB" },
  { value: "Elasticsearch", label: "Elasticsearch" },
  { value: "Solr", label: "Solr" },
  { value: "Neo4j", label: "Neo4j" },
  { value: "ArangoDB", label: "ArangoDB" },
  { value: "JanusGraph", label: "JanusGraph" },
  { value: "Redis", label: "Redis" },
  { value: "Memcached", label: "Memcached" },
  { value: "Riak", label: "Riak" },
  { value: "Google Cloud Spanner", label: "Google Cloud Spanner" },
  { value: "Google Cloud Firestore", label: "Google Cloud Firestore" },
  { value: "Google Cloud Datastore", label: "Google Cloud Datastore" },
  { value: "PostgreSQL", label: "PostgreSQL" },
  { value: "MySQL", label: "MySQL" },
  { value: "MariaDB", label: "MariaDB" },
  { value: "SQLite", label: "SQLite" },
  { value: "Oracle Database", label: "Oracle Database" },
  { value: "Microsoft SQL Server", label: "Microsoft SQL Server" },
  { value: "IBM DB2", label: "IBM DB2" },
];
